# Python Crash Course - Episode 2

Preliminaries: importing modules.

In Python, you use the `import` keyword to make code in one module available in another. You may want to import your own code, for example a library of functions you want to access (without re-defining everything), or a class (an object-contructor script). This is really helpful for organizing your code.

You can also import modules and packages available online (after download and installation).
Each module/package has online documentation explaining the usage of each function/class.
 Here some examples:


*   [math module](https://docs.python.org/3/library/math.html)
*   [numpy module](https://numpy.org/doc/stable/index.html)


In [4]:
import math # This module provides access to the mathematical functions defined by the C standard.

p = math.pi
math.sin(0.5*p)


1.0

In [5]:
# you can also give the module you import a nickname
import math as m

e = m.e
m.log(e)

1.0

In [7]:
# if you know you are going to use specific constants/functions from a module, you can decide to import those and nothing else
from math import pi,sin

sin(0.5*pi)


1.0

Preliminaries: matrices as lists of lists.

Write a function, `symmetryCheck`, that takes as input a matrix, expressed as a list of lists, and determines whether or not the matrix is symmetric. The function should return the strings `not symmetric` or `symmetric`. You may not use any obvious builtin function.

In [60]:
# hints on accessing elements
l1 = [i for i in range(5)]
l2 = [2*i for i in range(3)]

lols = [l1,l2]

#print(lols)
lols[1][0:2]
#lols[:][1]

[0, 2]

In [119]:
def symmetryCheck(A):
    # your code here
    c = len(A)
    r = len(A[0])
    if r != c:
        return 'not symmetric'
    for row in range(r):
      column = [A[col][row] for col in range(c)]
      if (A[row][:] != column):
        return 'not symmetric'
    return 'symmetric'

In [67]:
# test case 1
A = [[1, 2, 3], [2, 1, 3]]
assert(symmetryCheck(A) == 'not symmetric')
print('Test case passed!!!')

Test case passed!!!


In [45]:
# test case 2
A = [[1, 2, 3], [2, 1, 3], [2, 1, 3]]
assert(symmetryCheck(A) == 'not symmetric')
print('Test case passed!!!')

Test case passed!!!


In [46]:
# test case 3
A = [[1, 2, 3], [2, 1, 3], [3, 3, 3]]
assert(symmetryCheck(A) == 'symmetric')
print('Test case passed!!!')

Test case passed!!!


## NumPy - the fundamental package for scientific computing in Python

It is a Python library that provides a multidimensional array object, various derived objects (such as matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

[ref. [Numpy documentation](https://numpy.org/doc/stable/index.html)]

In [61]:
import numpy as np

The object around which the package is built is the `np.array`, a data structure that differs from lists by the following
* While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous.
* NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use.
* The indexing and element access is similar to the one in Matlab.

An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. Key attributes:

* The elements are all of the same type, referred to as the array dtype.
* The rank of the array is the number of dimensions `ndim`.
* The shape of the array is a tuple of integers giving the size of the array along each dimension.

In [85]:
b = np.array([1.,2,3])
print(b)
print()
print(["type:  ", b.dtype])
print(["rank:  ", b.ndim])
print(["shape: ", b.shape])

[1. 2. 3.]

['type:  ', dtype('float64')]
['rank:  ', 1]
['shape: ', (3,)]


In [84]:
A = np.array(A)
print(A)
print()
print(["type:  ", A.dtype])
print(["rank:  ", A.ndim])
print(["shape: ", A.shape])

[[1 2 3]
 [2 1 3]]

['type:  ', dtype('int64')]
['rank:  ', 2]
['shape: ', (2, 3)]


Besides creating an array from a sequence of elements, you can easily create an array filled with 0’s or 1's. Or filled with a range of elements or even linearly spaces numbers in an interval.

In [90]:
np.zeros(shape=(4,4),dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [93]:
np.ones(shape=(5,1),dtype = float)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [97]:
a = -3 # start
b = 10 # stop
c = 2 # step
np.arange(a,b,c)

array([-3, -1,  1,  3,  5,  7,  9])

In [99]:
a = -3 # start
b = 10 # stop
c = 5 # number of elements
np.linspace(a,b,c)


array([-3.  ,  0.25,  3.5 ,  6.75, 10.  ])

Indexing and slicing of NumPy arrays:

In [109]:
A = np.random.randint(-10,10,(5,3)) # low, high, shape
print(A)
A[:,1:3]

[[ -1  -5  -3]
 [ -6  -4  -3]
 [ -4   7  -3]
 [ -7   3   4]
 [ -3  -9 -10]]


array([[ -5,  -3],
       [ -4,  -3],
       [  7,  -3],
       [  3,   4],
       [ -9, -10]])

Exercise: rewrite the function SymmetryCheck code using arrays instead of lists.

In [123]:
def symmetryCheck_arrays(A):
    # your code here
    r,c = A.shape
    if r != c:
        return 'not symmetric'
    for row in range(r):
      if any(A[row,:] != A[:,row]):
        return 'not symmetric'
    return 'symmetric'

In [124]:
b = np.random.randint(-100, 100, size = (10, 10))
test = (b + b.T)
test1 = (symmetryCheck_arrays(test) == 'symmetric')
b = np.random.randint(-100, 100, size = (10, 10))
test2 = (symmetryCheck_arrays(b) == 'not symmetric')

if test1 and test2:
  print('Test cases passed!!!')
else:
  print('Oh no :(')

Test cases passed!!!


One of the disclaimers with which we started talking about Numpy arrays was an efficiency boost, let's check!

In [129]:
from binascii import b2a_hex
import time
# using lists
b = np.random.randint(-100, 100, size = (1000, 1000))
b1 = (b + b.T).tolist()
b2 = np.random.randint(-100, 100, size = (1000, 1000)).tolist()

start_time = time.time()

test1 = (symmetryCheck(b1) == 'symmetric')
test2 = (symmetryCheck(b2) == 'not symmetric')

end_time_lists = time.time() - start_time


# using arrays
b = np.random.randint(-100, 100, size = (10, 10))
b1 = (b + b.T)
b2 = np.random.randint(-100, 100, size = (10, 10))

start_time = time.time()
test1 = (symmetryCheck_arrays(b1) == 'symmetric')
test2 = (symmetryCheck_arrays(b2) == 'not symmetric')

end_time_arrays = time.time() - start_time

print("The execution time for symmetryCheck is ", end_time_lists)
print("The execution time for symmetryCheck_arrays is ", end_time_arrays)

The execution time for symmetryCheck is  0.124725341796875
The execution time for symmetryCheck_arrays is  0.00014472007751464844


## Some other useful functions

1.   Using `np.array.reshape()` will give a new shape to an array without changing the data. Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array (use the attribute `size` to check!).
2.   You can add, and sort elements of an array by using the functions `np.concatenate((a,b),axis=0)` and `np.sort(a)`



In [155]:
a = np.arange(6)
b = np.arange(10,15,3)
c = np.concatenate((b,a))
#print(c)

d = np.sort(c)
#print(d)

e = d[:4]
#print(e)

f = d[4:]
#print(f)


g = e.reshape((2,2))
h = f.reshape((2,2))

#print(g)
#print(h)

i = np.concatenate((g,h),axis=0)
np.sort(i,axis=0)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [10, 13]])

## Exercises

1. Looking at the official Numpy documentation, write a function `my_linear_solver` for computing the solution of linear systems $Ax=b$ as $x=A^{-1}b$.
2. Confront the solution with `np.linalg.solve()`. Which method is faster?


In [156]:
def my_linear_solver(A,b):
  # your code here
  Am1 = np.linalg.inv(A)
  x = np.matmul(Am1,b)
  return x

In [173]:
A = np.random.randint(-10,10,(1000,1000))
b = np.random.randint(-10,10,(1000,1))

start_time = time.time()
my_solution = my_linear_solver(A,b)
mytime = time.time() - start_time
print(mytime)

start_time = time.time()
linalg_solution = np.linalg.solve(A,b)
linalgtime = time.time() - start_time
print(linalgtime)


0.20962977409362793
0.06490015983581543


$$\begin{cases}
x+y+z=3\\
x^2 + y^2 + z^2 = 5\\
e^x + xy+xz = 1
\end{cases}
$$

solution $[0,2,1]$

In [ ]:
def Newton_system(F, J, x0, tol):
    F_value = F(x0)
    F_norm = np.linalg.norm(F_value, ord=2)  # l2 norm of vector
    iteration_counter = 0
    while abs(F_norm) > tol and iteration_counter < 100:
        delta = np.linalg.solve(J(x), -F_value)
        x = x + delta
        F_value = F(x)
        F_norm = np.linalg.norm(F_value, ord=2)
        iteration_counter += 1

    # Here, either a solution is found, or too many iterations
    if abs(F_norm) > tol:
        iteration_counter = -1
    return x, iteration_counter